language: python
python:
  - "2.7"
  - "3.4"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
addons:
  postgresql: "9.4"
before_script:
  - psql -c "CREATE DATABASE hc;" -U postgres
  - mysql -e 'CREATE DATABASE hc;'
  - python manage.py makemigrations
  - python manage.py migrate
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
