language: python
python:
  - "2.7"
  - "3.4"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
  global:
    - TWILIO_ACCOUNT_SID='dummy'
    - TWILIO_AUTH_TOKEN='dummy'
    - TWILIO_FROM_='dummy'
    - TELEGRAM_TOKEN='secrete'
addons:
  postgresql: "9.4"
before_script:
  - psql -c "CREATE DATABASE hc;" -U postgres
  - mysql -e 'CREATE DATABASE hc;'
  - python manage.py migrate
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip
