# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='escalation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_interval',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='priority',
            field=models.IntegerField(default=2),
        ),
    ]
