# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_check_reverse_grace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='reverse_grace',
            new_name='reverse',
        ),
    ]
