# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170914_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_after',
            field=models.DurationField(null=True),
        ),
    ]
