# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170912_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='escalation_status',
            field=models.BooleanField(default=False),
        ),
    ]
