# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_escalation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='escalation_status',
            new_name='escalation_down',
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_up',
            field=models.BooleanField(default=False),
        ),
    ]
