# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20170915_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_status',
        ),
        migrations.AlterField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(null=True),
        ),
    ]
